# Numpy

In [56]:
import numpy as np

## 1. Create

### 1.1. Arrays from Python List

* [`np.array(py_list)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html): Numpy array from python list `py_list`

In [57]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### 1.2. Arrays filled with single value

* [`np.zeros(dim)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): Array full of zeros with dimensions given by `dim: tuple`

In [58]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

* [`np.ones(dim)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): Array full of ones with dimensions given by `dim: tuple`

In [59]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 1.3. Arrays generated from a range

* [`np.arange(start, stop, step)`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html): Array generated from the interval [`start`, `stop`] with stepsize `step`

In [60]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

* [`np.linspace(start, stop, num)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html): Array of evenly spaced numbers over an interval [`start`, `stop`] with `num` samples

In [61]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 1.4. Identity matrix

* [`np.eye(d1, d2, ...)`](https://numpy.org/devdocs/reference/generated/numpy.eye.html): identity matrix

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.5. Random arrays

* [`np.random.rand(d1, d2, ...)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html): Array of random numbers from a **uniform distribution over [0, 1)**

In [63]:
np.random.rand(2, 3)

array([[0.52045215, 0.41602821, 0.30792845],
       [0.24098193, 0.01397551, 0.88455005]])

* [`np.random.randn`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html): Array of random numbers from a **standard normal distribution**

In [64]:
np.random.randn(2, 3)

array([[-0.04326562, -1.62610118, -0.80611578],
       [ 0.78051602,  0.29855186, -0.69190775]])

* [`np.random.randint(low, high, dim)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html): Array with dimension `dim: tuple` of random integers from a **discrete uniform distribution [low, high)**

In [65]:
np.random.randint(0, 10, (2, 3))

array([[2, 6, 5],
       [9, 0, 5]])

## 2. Reshape

* [`arr.reshape(d1, d2, ...)`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [66]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.arange(1, 7).reshape(2, 3).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 3. Min/max values

In [68]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
a.max()

9

In [70]:
a.min()

1

## 4. Access/Select

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 4.1. Access single element

In [72]:
assert a[0][0] == a[0, 0]
a[0, 0]

1

### 4.2. Access single row/column

In [73]:
a[:, 2]

array([3, 6, 9])

In [74]:
a[1, :]

array([4, 5, 6])

### 4.3. Access multiple rows/columns

In [75]:
a[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [76]:
a[0:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

**Important note**: accessing one or multiple rows/columns can be done by using the slice operator `:`. The slice operator on numpy array **does not create a new array, but instead point to the same location of the original array**.

In [77]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
b = a[0:2, :]
b[:] = 9

In [79]:
a

array([[9, 9, 9],
       [9, 9, 9],
       [7, 8, 9]])

### 4.4. Conditional selection with Boolean array indexing

More on this: [here](https://numpy.org/doc/stable/reference/arrays.indexing.html#boolean-array-indexing)

#### 4.4.1. Conditional selection on 1d array

In [80]:
a = np.random.randint(0, 10, 5)
print(a)

[1 7 8 9 7]


In [81]:
mask = a > 5
print(mask)

[False  True  True  True  True]


In [82]:
a[mask]

array([7, 8, 9, 7])

In [83]:
a[mask] = 0

In [84]:
a

array([1, 0, 0, 0, 0])

#### 4.4.2. Conditional selection on 2d array

In [85]:
a = np.random.randint(0, 3, (10, 3))
print(a)

[[1 2 0]
 [0 2 0]
 [1 2 1]
 [0 0 2]
 [0 1 2]
 [2 0 2]
 [0 2 2]
 [0 1 2]
 [1 2 2]
 [0 2 1]]


In [86]:
mask = a[:, 0] == 1 # mask to select all rows having 1 in the first column
print(mask)

[ True False  True False False False False False  True False]


In [87]:
a[mask, :]

array([[1, 2, 0],
       [1, 2, 1],
       [1, 2, 2]])

## 5. Matrix Operations

### 5.1. Element-wise operations

In [88]:
a = np.array([[3, 2, 5],
              [4, 7, 1]])
b = np.array([[2, 1, 0],
              [3, 2, 5]])
print(a + b)
print(a - b)
print(a * b)

[[5 3 5]
 [7 9 6]]
[[ 1  1  5]
 [ 1  5 -4]]
[[ 6  2  0]
 [12 14  5]]


### 5.2. Broadcasting

Read:
* [Basic broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)
* [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy)

In [89]:
a * 3

array([[ 9,  6, 15],
       [12, 21,  3]])

### 5.3. Matrix multiplication

In [90]:
a @ b.T

array([[ 8, 38],
       [15, 31]])

In [91]:
np.matmul(a, b.T)

array([[ 8, 38],
       [15, 31]])