# Numpy

In [4]:
import numpy as np

## 1. Create

### 1.1. Arrays from Python List

* [`np.array(py_list)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html): Numpy array from python list `py_list`

In [31]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### 1.2. Arrays filled with single value

* [`np.zeros(dim)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): Array full of zeros with dimensions given by `dim: tuple`

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

* [`np.ones(dim)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): Array full of ones with dimensions given by `dim: tuple`

In [26]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 1.3. Arrays generated from a range

* [`np.arange(start, stop, step)`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html): Array generated from the interval [`start`, `stop`] with stepsize `step`

In [28]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

* [`np.linspace(start, stop, num)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html): Array of evenly spaced numbers over an interval [`start`, `stop`] with `num` samples

In [29]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 1.4. Identity matrix

* [`np.eye(d1, d2, ...)`](https://numpy.org/devdocs/reference/generated/numpy.eye.html): identity matrix

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.5. Random arrays

* [`np.random.rand(d1, d2, ...)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html): Array of random numbers from a **uniform distribution over [0, 1)**

In [25]:
np.random.rand(2, 3)

array([[0.50966296, 0.15312415, 0.25807248],
       [0.28648826, 0.61188562, 0.06306475]])

* [`np.random.randn`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html): Array of random numbers from a **standard normal distribution**

In [33]:
np.random.randn(2, 3)

array([[ 0.64552952, -0.61325071,  0.10082432],
       [ 1.68970234, -1.08909944,  0.048324  ]])

* [`np.random.randint(low, high, dim)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html): Array with dimension `dim: tuple` of random integers from a **discrete uniform distribution [low, high)**

In [34]:
np.random.randint(0, 10, (2, 3))

array([[8, 9, 5],
       [4, 6, 2]])

## 2. Reshape

* [`arr.reshape(d1, d2, ...)`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [38]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.arange(1, 7).reshape(2, 3).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 3. Min/max values

In [42]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
a.max()

9

In [44]:
a.min()

1

## 4. Access/Select

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 4.1. Access single element

In [62]:
assert a[0][0] == a[0, 0]
a[0, 0]

1

### 4.2. Access single row/column

In [63]:
a[:, 2]

array([3, 6, 9])

In [64]:
a[1, :]

array([4, 5, 6])

### 4.2. Access multiple rows/columns

In [65]:
a[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [66]:
a[0:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

**Important note**: accessing one or multiple rows/columns can be done by using the slice operator `:`. The slice operator on numpy array **does not create a new array, but instead point to the same location of the original array**.

In [67]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
b = a[0:2, :]
b[:] = 9

In [73]:
a

array([[9, 9, 9],
       [9, 9, 9],
       [7, 8, 9]])

## 5. Matrix Operations

### 5.1. Element-wise operations

In [87]:
a = np.array([[3, 2, 5],
              [4, 7, 1]])
b = np.array([[2, 1, 0],
              [3, 2, 5]])
print(a + b)
print(a - b)
print(a * b)

[[5 3 5]
 [7 9 6]]
[[ 1  1  5]
 [ 1  5 -4]]
[[ 6  2  0]
 [12 14  5]]


### 5.2. Broadcasting

Read:
* [Basic broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)
* [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy)

In [80]:
a * 3

array([[ 9,  6, 15],
       [12, 21,  3]])

### 5.3. Matrix multiplication

In [82]:
a @ b.T

array([[ 8, 38],
       [15, 31]])

In [86]:
np.matmul(a, b.T)

array([[ 8, 38],
       [15, 31]])